version: '3.1'
services:
  mongo:
    image: mongo:4.4
    container_name: mongo
    ports:
      - 27090:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=12345
    volumes:
      - ./mongodb_data:/data/db
    networks:
      - backend
networks:
  backend:
    external:
      name: proxy

